/** Human readings of recorded evidence, shared by terminal and browser. */
export const runReadingEnglish = {
	"reading.check": "A recorded check did not pass",
	"reading.execution": "The agent could not finish this case",
	"reading.executionUnknown": "The run ended without a recorded explanation.",
	"reading.executionLimit": "Repair the execution problem before judging the answer. This incomplete run does not establish a behavioral failure.",
	"reading.pass": "This case passed its recorded checks",
	"reading.passLimit": "Passing this case covers only its recorded checks. It does not establish readiness for other situations.",
	"reading.judgeUncertain": "The evaluator could not decide",
	"reading.judgeLimit": "At least one evaluator declined to decide. That uncertainty must be resolved before treating its result as an agent defect.",
	"reading.ticketMissing": "The expected ticket was not recorded",
	"reading.ticketAccountMissing": "The test state contains no ticket for contract {account}.",
	"reading.ticketNotFound": "The check did not find the expected ticket.",
	"reading.resultMissing": "The expected result of the action was not recorded",
	"reading.resultDifferent": "The action did not leave the expected result",
	"reading.worldLimit": "These checks inspect the declared test state. The answer is quoted separately; the record does not establish the underlying cause or what happened in production.",
	"reading.worldFieldMissing": "The test state has no {path}; this case expected {expected}.",
	"reading.worldFieldDifferent": "The test state records {path} as {actual}; this case expected {expected}.",
	"reading.sourceUnused": "The needed source was returned, but the answer failed the source check",
	"reading.sourceMissing": "The search did not return the needed source",
	"reading.searchSkipped": "The recorded conversation contains no source search",
	"reading.sourceCheck": "The answer failed the source check",
	"reading.noSearch": "No executed knowledge search is recorded.",
	"reading.sourceReturned": "The recorded search result contains a source required by this case.",
	"reading.sourceNotReturned": "The readable search results contain none of the sources required by this case.",
	"reading.sourceCheckObserved": "The answer neither cites {source} nor has enough text overlap with it to pass the recorded check.",
	"reading.sourceLimit": "The source check measures citation or text overlap, not whether every claim follows from the source. The record does not establish why the agent answered this way.",
	"reading.toolMissing": "The required action {tool} is not recorded",
	"reading.toolLimit": "The required tool check did not pass. That alone does not establish the final business state or why the action was missed.",
	"reading.unknownLimit": "The recorded reason is shown as evidence. No more specific explanation can be derived safely from this check.",
	"reading.traceMissing": "The verified conversation is unavailable; no answer or sequence is reconstructed.",
	"reading.traceClipped": "The conversation exceeds the preview limits; this excerpt may omit context. No missing content is reconstructed.",
	"reading.moreChecks": "{count} other failed checks remain in the detailed record.",
	"reading.worldUndeclared": "The case does not define how to verify the action result",
	"reading.worldUndeclaredLimit": "Define the test state before interpreting this failure as an agent mistake.",
	"reading.eyebrow": "What this recorded case shows",
	"reading.expected": "The case expected",
	"reading.observed": "What was recorded",
	"reading.answer": "The agent answered",
	"reading.change": "Change and recheck",
	"reading.noChange": "No verified change is linked to this case yet. The failure above is a starting point, not proof of a fix.",
	"reading.caseChange": "This case across recorded repetitions: {before} → {after}. Read the complete comparison before accepting the change.",
	"reading.noiseCheck": "This is a repeated measurement of the same revision, not a change to the agent.",
	"reading.uncertain": "What this does not establish",
	"reading.quotedClip": "The quotation is shortened; open the conversation for the bounded record.",
	"reading.openChecks": "See the recorded reasons",
	"reading.issueWorld": "The expected action result is missing or differs",
	"reading.issueSource": "The answer failed the source check",
	"reading.issueTool": "A required action is missing",
	"reading.issueOutput": "The answer misses a required detail",
	"reading.issueExecution": "The agent could not complete the run",
	"reading.example": "One recorded example",
	"reading.diagnosisIncompatible": "This stored diagnosis uses an incompatible classification",
	"reading.diagnosisRecovery": "The verified checks disagree with the saved diagnostic status. An older diagnosis may use the previous classification. Run a new evaluation and diagnosis; the existing record is preserved because candidate evidence can depend on its exact bytes.",
} as const;

export const runReadingRussian: Record<keyof typeof runReadingEnglish, string> = {
	"reading.check": "Записанная проверка не пройдена",
	"reading.execution": "Агент не смог завершить этот кейс",
	"reading.executionUnknown": "Прогон завершился без записанного объяснения.",
	"reading.executionLimit": "Сначала нужно устранить проблему выполнения. По незавершённому прогону нельзя оценить качество ответа.",
	"reading.pass": "Этот кейс прошёл записанные проверки",
	"reading.passLimit": "Успех относится к проверкам этого кейса. Он не доказывает готовность агента к другим ситуациям.",
	"reading.judgeUncertain": "Оценщик не смог вынести решение",
	"reading.judgeLimit": "Хотя бы один оценщик не смог вынести решение. Эту неопределённость нельзя считать доказанной ошибкой агента.",
	"reading.ticketMissing": "Ожидаемая заявка не появилась",
	"reading.ticketAccountMissing": "В состоянии теста нет заявки по договору {account}.",
	"reading.ticketNotFound": "Проверка не нашла ожидаемую заявку.",
	"reading.resultMissing": "Ожидаемый результат действия не появился",
	"reading.resultDifferent": "Результат действия не соответствует ожидаемому",
	"reading.worldLimit": "Проверки смотрят на заданное состояние теста. Ответ приведён отдельно; запись не устанавливает первопричину или последствия в продакшене.",
	"reading.worldFieldMissing": "В состоянии теста нет {path}; в этом кейсе ожидалось {expected}.",
	"reading.worldFieldDifferent": "В состоянии теста {path} равно {actual}; в этом кейсе ожидалось {expected}.",
	"reading.sourceUnused": "Нужный источник найден, но ответ не прошёл проверку по нему",
	"reading.sourceMissing": "Поиск не вернул нужный источник",
	"reading.searchSkipped": "В записанном разговоре нет поиска по источникам",
	"reading.sourceCheck": "Ответ не прошёл проверку по источнику",
	"reading.noSearch": "Выполненный поиск по знаниям не записан.",
	"reading.sourceReturned": "В записанном результате поиска есть источник, который требовался в этом кейсе.",
	"reading.sourceNotReturned": "В доступных результатах поиска нет ни одного источника, требовавшегося в этом кейсе.",
	"reading.sourceCheckObserved": "В ответе нет ссылки на {source} и достаточного совпадения с его текстом, чтобы пройти записанную проверку.",
	"reading.sourceLimit": "Проверка измеряет цитирование или совпадение текста, а не обоснованность каждого утверждения. Запись не объясняет, почему агент ответил именно так.",
	"reading.toolMissing": "Нужное действие {tool} не записано",
	"reading.toolLimit": "Проверка нужного инструмента не пройдена. Само по себе это не устанавливает итоговое состояние бизнеса или причину пропуска.",
	"reading.unknownLimit": "Показано записанное обоснование. Из этой проверки нельзя надёжно вывести более конкретное объяснение.",
	"reading.traceMissing": "Проверенный разговор недоступен; ответ и порядок действий не восстанавливаются по догадке.",
	"reading.traceClipped": "Разговор превышает ограничения просмотра; в отрывке может не хватать контекста. Пропущенное содержимое не восстанавливается по догадке.",
	"reading.moreChecks": "Других проваленных проверок в подробной записи: {count}.",
	"reading.worldUndeclared": "В кейсе не задано, как проверить результат действия",
	"reading.worldUndeclaredLimit": "Сначала нужно задать состояние теста; пока этот сбой нельзя трактовать как ошибку агента.",
	"reading.eyebrow": "Что видно в этом кейсе",
	"reading.expected": "В кейсе ожидалось",
	"reading.observed": "Что записано",
	"reading.answer": "Агент ответил",
	"reading.change": "Правка и повторная проверка",
	"reading.noChange": "С этим кейсом пока не связана проверенная правка. Описанный сбой — отправная точка, а не доказательство исправления.",
	"reading.caseChange": "Этот кейс в записанных повторах: {before} → {after}. Перед принятием правки нужно прочитать общее сравнение.",
	"reading.noiseCheck": "Это повторное измерение одной версии, а не правка агента.",
	"reading.uncertain": "Чего эта запись не доказывает",
	"reading.quotedClip": "Цитата сокращена; ограниченная запись доступна в разговоре.",
	"reading.openChecks": "Посмотреть записанные основания",
	"reading.issueWorld": "Ожидаемый результат действия отсутствует или отличается",
	"reading.issueSource": "Ответ не прошёл проверку по источнику",
	"reading.issueTool": "Нужное действие не выполнено",
	"reading.issueOutput": "В ответе не хватает обязательной детали",
	"reading.issueExecution": "Агент не смог завершить прогон",
	"reading.example": "Один записанный пример",
	"reading.diagnosisIncompatible": "Сохранённая диагностика использует несовместимую классификацию",
	"reading.diagnosisRecovery": "Проверенные результаты расходятся с сохранённым статусом диагностики. Старая запись могла использовать прежнюю классификацию. Нужен новый прогон с новой диагностикой. Существующая запись сохранена: от её точного содержимого могут зависеть доказательства правки.",
};
