/** Copy owned by the read-only Evidence screens. Artifact text is never translated. */
export const evidenceEnglish = {
	"evidence.notComparable": "Not comparable",
	"evidence.invalidComparison": "These runs used different or invalid conditions. The recorded answers can be inspected, but they cannot establish an improvement.",
	"evidence.recordedReasons": "Reasons retained in the original decision record:",
	"evidence.comparisonNotices": "Comparison limitations: {count}",
	"evidence.excluded-infrastructure": "Excluded: execution error",
	"evidence.excluded-incomplete": "Excluded: missing repetitions",
	"evidence.excludedNote": "This pair is excluded from the verdict; these answers do not establish an improvement.",
	"evidence.brand": "AHDE Evidence",
	"evidence.comparison": "What changed in the agent",
	"evidence.comparisonIntro": "Compare the answers and actions behind the numbers.",
	"evidence.examples": "Before and after",
	"evidence.exampleNote": "Showing {shown} of {total} task pairs, regressions first. Each card uses the earliest matching recorded repetition; the verdict uses all eligible repetitions.",
	"evidence.baseline": "Before",
	"evidence.candidate": "After",
	"evidence.openRun": "Open full conversation",
	"evidence.noSample": "No matching recorded repetition is available for this task.",
	"evidence.noAnswer": "No final answer is available in the verified trace.",
	"evidence.noInput": "Case input is unavailable.",
	"evidence.checks": "Checks of actions and state",
	"evidence.moreChecks": "{count} more checks in the full conversation",
	"evidence.noTools": "No executed tools recorded",
	"evidence.reportedTools": "Agent-reported tools",
	"evidence.executedTools": "Executed tools",
	"evidence.toolErrors": "Tool errors",
	"evidence.noToolsTrace": "Tool names are unavailable in the verified trace.",
	"evidence.changedScore": "Score across repetitions",
	"evidence.improved": "improved",
	"evidence.regressed": "regressed",
	"evidence.unchanged": "unchanged",
	"evidence.pass": "pass",
	"evidence.fail": "fail",
	"evidence.error": "error",
	"evidence.metadata": "Recorded identities and details",
	"evidence.passRate": "Pass rate",
	"evidence.passed": "Passed",
	"evidence.meanScore": "Mean score",
	"evidence.errors": "Errors",
	"evidence.failureModes": "Failure modes",
	"evidence.allPassRate": "All-pass rate",
	"evidence.taskFlips": "Task score changes",
	"evidence.costRatio": "Cost ratio",
	"evidence.latencyRatio": "Latency ratio",
	"evidence.tokenRatio": "Token ratio",
	"evidence.sealed": "Sealed verdict",
	"evidence.sealedDesign": "{tasks} cases × {repetitions} repetitions",
	"evidence.sealedExcluded": "{count} excluded",
	"evidence.sealedNote": "This is a relative comparison, not an absolute readiness score. Sealed cases, identifiers, and traces are never rendered here.",
	"evidence.sealedUnknown": "pass; the recorded evidence does not establish whether it improved",
	"evidence.noSealed": "No sealed holdout comparison is recorded for this candidate.",
	"evidence.flipNote": "Per-task flips are flags for review; the verdict above comes only from the paired interval.",
	"evidence.noRuns": "No runs match this filter.",
	"evidence.noGraders": "no graders",
	"evidence.traceUnavailable": "trace unavailable",
	"evidence.executedCount": "{count} executed",
	"evidence.reportedCount": "{count} reported",
	"evidence.errorCount": "{count} errors",
	"evidence.filterPlaceholder": "Filter by task id or input text",
	"evidence.filterLabel": "Filter runs",
	"evidence.filterCount": "{shown} of {total} rows",
	"evidence.all": "all",
	"evidence.clearMode": "clear mode filter",
	"evidence.noModes": "No failure modes: the verified diagnosis found nothing to group.",
	"evidence.proposalEligible": "An exact change can be prepared for human review.",
	"evidence.proposalBlocked": "The evidence does not yet support preparing a change. Resolve the measurement issues first.",
	"evidence.design": "{tasks} cases × {repetitions} repetitions · {runs} runs",
	"evidence.model": "Model",
	"evidence.dataset": "Dataset",
	"evidence.user": "user",
	"evidence.assistant": "assistant",
	"evidence.finalAnswer": "final answer",
	"evidence.thinking": "thinking",
	"evidence.tool": "tool",
	"evidence.arguments": "arguments",
	"evidence.result": "result",
	"evidence.clipped": "clipped",
	"evidence.reportedOnly": "agent-reported, not host-verified",
	"evidence.noResult": "no result recorded",
	"evidence.ok": "ok",
	"evidence.noTrace": "No trace is recorded for this run.",
	"evidence.noTurns": "The recorded trace holds no renderable turns.",
	"evidence.noGraderResults": "This run recorded no grader results.",
	"evidence.assertionsSummary": "The record keeps {passed}/{total} assertions; per-assertion evidence is not available for this run.",
	"evidence.jury": "Jury",
	"evidence.juror": "juror",
	"evidence.choice": "choice",
	"evidence.hostNote": "Every sentence above is assembled by the host from recorded fields — the grader results, the bounded trace, the stored diagnosis, and a Candidate's own comparison. No model wrote it.",
	"evidence.systemInstructions": "System instructions",
	"evidence.systemUnavailable": "The Target's system instructions are not recorded in session.jsonl; this transcript starts at the case input.",
	"evidence.caseInput": "Case input",
	"evidence.allRuns": "all runs",
	"evidence.diagnosisDetails": "Read the complete explanation",
	"evidence.traceNotice": "{count} transcript entries rendered{clipped}{omitted}. Credential-shaped text is redacted; the protected artifact on disk is unchanged.",
	"evidence.traceClipped": "; longer content is clipped",
	"evidence.traceOmitted": "; {count} later trace records omitted",
} as const;

export const evidenceRussian: Record<keyof typeof evidenceEnglish, string> = {
	"evidence.notComparable": "Несопоставимо",
	"evidence.invalidComparison": "Условия этих прогонов различаются или недействительны. Ответы можно изучить, но они не доказывают улучшение.",
	"evidence.recordedReasons": "Основания из исходной записи решения:",
	"evidence.comparisonNotices": "Ограничения сравнения: {count}",
	"evidence.excluded-infrastructure": "Исключён: ошибка выполнения",
	"evidence.excluded-incomplete": "Исключён: не хватает повторов",
	"evidence.excludedNote": "Пара исключена из вердикта; эти ответы не доказывают улучшение.",
	"evidence.brand": "AHDE · Доказательства",
	"evidence.comparison": "Что изменилось в агенте",
	"evidence.comparisonIntro": "Сравните ответы и действия, которые стоят за цифрами.",
	"evidence.examples": "До и после",
	"evidence.exampleNote": "Показано {shown} из {total} пар кейсов, сначала ухудшения. В карточке — первый общий записанный повтор; вердикт учитывает все допустимые повторы.",
	"evidence.baseline": "До правки",
	"evidence.candidate": "После правки",
	"evidence.openRun": "Открыть весь диалог",
	"evidence.noSample": "Для этого кейса нет записанного повтора, общего для двух версий.",
	"evidence.noAnswer": "В проверенной записи нет доступного итогового ответа.",
	"evidence.noInput": "Вход кейса недоступен.",
	"evidence.checks": "Проверки действий и состояния",
	"evidence.moreChecks": "Ещё {count} проверок в полном диалоге",
	"evidence.noTools": "Выполненные инструменты не записаны",
	"evidence.reportedTools": "Инструменты со слов агента",
	"evidence.executedTools": "Выполнено инструментов",
	"evidence.toolErrors": "Ошибки инструментов",
	"evidence.noToolsTrace": "В проверенной записи нет доступных имён инструментов.",
	"evidence.changedScore": "Балл по всем повторам",
	"evidence.improved": "стало лучше",
	"evidence.regressed": "стало хуже",
	"evidence.unchanged": "без изменений",
	"evidence.pass": "пройдено",
	"evidence.fail": "не пройдено",
	"evidence.error": "ошибка",
	"evidence.metadata": "Идентификаторы и детали записи",
	"evidence.passRate": "Доля успешных",
	"evidence.passed": "Пройдено",
	"evidence.meanScore": "Средний балл",
	"evidence.errors": "Ошибки",
	"evidence.failureModes": "Типы сбоев",
	"evidence.allPassRate": "Доля успешных прогонов",
	"evidence.taskFlips": "Изменение балла кейсов",
	"evidence.costRatio": "Изменение цены",
	"evidence.latencyRatio": "Изменение задержки",
	"evidence.tokenRatio": "Изменение токенов",
	"evidence.sealed": "Закрытый экзамен",
	"evidence.sealedDesign": "Кейсов: {tasks} × повторов: {repetitions}",
	"evidence.sealedExcluded": "исключено: {count}",
	"evidence.sealedNote": "Это сравнение версий, а не абсолютная оценка готовности. Кейсы, идентификаторы и диалоги закрытого экзамена здесь не показываются.",
	"evidence.sealedUnknown": "пройден; запись не позволяет уточнить, доказано ли улучшение",
	"evidence.noSealed": "Для этого кандидата не записано сравнение на закрытом экзамене.",
	"evidence.flipNote": "Изменения отдельных кейсов требуют внимания; вердикт выше определяется только парным доверительным интервалом.",
	"evidence.noRuns": "Нет прогонов по этому фильтру.",
	"evidence.noGraders": "нет проверок",
	"evidence.traceUnavailable": "запись недоступна",
	"evidence.executedCount": "выполнено: {count}",
	"evidence.reportedCount": "со слов агента: {count}",
	"evidence.errorCount": "ошибок: {count}",
	"evidence.filterPlaceholder": "Найти кейс или текст обращения",
	"evidence.filterLabel": "Поиск по прогонам",
	"evidence.filterCount": "Строк: {shown} из {total}",
	"evidence.all": "все",
	"evidence.clearMode": "сбросить тип сбоя",
	"evidence.noModes": "Типы сбоев не найдены: проверенный диагноз не обнаружил ошибок для группировки.",
	"evidence.proposalEligible": "Можно подготовить точную правку для вашего ревью.",
	"evidence.proposalBlocked": "Доказательств пока недостаточно для правки. Сначала нужно устранить проблемы измерения.",
	"evidence.design": "Кейсов: {tasks} × повторов: {repetitions} · прогонов: {runs}",
	"evidence.model": "Модель",
	"evidence.dataset": "Датасет",
	"evidence.user": "клиент",
	"evidence.assistant": "агент",
	"evidence.finalAnswer": "итоговый ответ",
	"evidence.thinking": "рассуждение",
	"evidence.tool": "инструмент",
	"evidence.arguments": "аргументы",
	"evidence.result": "результат",
	"evidence.clipped": "сокращён",
	"evidence.reportedOnly": "со слов агента, хостом не подтверждено",
	"evidence.noResult": "результат не записан",
	"evidence.ok": "успешно",
	"evidence.noTrace": "Диалог этого прогона не записан.",
	"evidence.noTurns": "В записи нет доступных реплик.",
	"evidence.noGraderResults": "В этом прогоне нет результатов проверок.",
	"evidence.assertionsSummary": "В записи сохранено {passed}/{total} утверждений; отдельные обоснования для них недоступны.",
	"evidence.jury": "Коллегия судей",
	"evidence.juror": "судья",
	"evidence.choice": "выбор",
	"evidence.hostNote": "Все пояснения собраны хостом из результатов проверок, ограниченной записи диалога, сохранённого диагноза и сравнения кандидата. Модель их не сочиняла.",
	"evidence.systemInstructions": "Системные инструкции",
	"evidence.systemUnavailable": "Системные инструкции агента не сохранены в записи; диалог начинается с входа кейса.",
	"evidence.caseInput": "Вход кейса",
	"evidence.allRuns": "все прогоны",
	"evidence.diagnosisDetails": "Полное объяснение",
	"evidence.traceNotice": "Показано записей диалога: {count}{clipped}{omitted}. Строки, похожие на ключи доступа, скрыты; исходный артефакт на диске не изменён.",
	"evidence.traceClipped": "; длинный текст сокращён",
	"evidence.traceOmitted": "; пропущено последующих записей: {count}",
};

