/** Copy owned by the read-only Evidence screens. Artifact text is never translated. */
export const evidenceEnglish = {
	"conversation.number": "Conversation {number}",
	"conversation.selected": "Selected conversation",
	"conversation.notGrouped": "This conversation and its checks are available. Recurring problems have not been grouped for this evaluation yet; ask Builder to analyze it when you need that overview.",
	"conversation.expected": "What the case required",
	"conversation.expectedDetails": "See the recorded checks below for this case's requirements.",
	"conversation.before": "What was recorded before",
	"conversation.after": "What was recorded after",
	"conversation.story": "Expectation and recorded outcome",
	"conversation.changeFiles": "Changed files: {paths}",
	"conversation.authorHypothesis": "The author's recorded hypothesis",
	"conversation.next": "What to check next",
	"conversation.nextReview": "Review the whole comparison, including regressions and excluded cases. A selected conversation cannot decide whether to accept the change.",
	"conversation.nextTerminal": "Return to Builder in the terminal to check whether this change can be accepted. It will recheck the current evidence and request the final decision.",
	"conversation.nextInconclusive": "This comparison is inconclusive. Resolve the recorded evidence limitations with Builder before deciding whether to accept the change.",
	"conversation.nextInvalid": "These results are not comparable. Ask Builder to resolve the differing evaluation conditions before running a new comparison.",
	"conversation.openEvaluation": "Open all recorded conversations",
	"conversation.openChanges": "Inspect the exact change",
	"conversation.historical": "Recorded evaluation under earlier rules",
	"conversation.historicalMeaning": "The conversations and results are preserved, but the evaluation rules have changed. Accepting this change requires a new measurement.",
	"conversation.historicalRules": "These results use {before}; the current evaluator is {after}. They describe the saved conversations and cannot authorize accepting the change today.",
	"conversation.historicalAction": "Rescore the saved conversations in Builder",
	"conversation.historicalLimit": "Regrading preserves the originals and does not call the agent again; model judges may still run. A decision to accept requires a new measurement, not just this retrospective regrade.",
	"workspace.checkCount": "{passed}/{total} passed",
	"workspace.moreFailed": "{count} more failed checks in the inspector",
	"workspace.title": "Evaluation workspace",
	"workspace.issues": "Issues",
	"workspace.allIssues": "All recorded runs",
	"workspace.observed": "Observed in this evaluation",
	"workspace.impact": "{affected}/{total} cases · {runs} runs",
	"workspace.reproduction": "Matching observations failed: {failed}/{total} ({rate})",
	"workspace.issueNote": "These groups describe recorded failures. They do not establish a root cause or production impact.",
	"workspace.runs": "Runs",
	"workspace.shown": "{shown} of {total} runs",
	"workspace.search": "Search",
	"workspace.searchNote": "Searches the recorded task id and bounded input preview.",
	"workspace.inspect": "Inspect run",
	"workspace.inspector": "Conversation inspector",
	"workspace.empty": "Choose a recorded run to inspect its conversation and checks.",
	"workspace.trajectory": "Recorded sequence",
	"workspace.trajectoryNote": "Original interaction order. Tool durations are recorded where available; this is not a distributed span tree.",
	"workspace.checks": "Checks and recorded explanation",
	"workspace.more": "Evaluation details and limitations",
	"workspace.keyboard": "Tab between controls. Use ↑ / ↓ on a run link to move through the list; Enter opens it.",
	"workspace.focusRuns": "Go to runs",
	"workspace.focusTrace": "Go to conversation",
	"workspace.outsideFilter": "This linked run belongs to the evaluation but is outside the current filters.",
	"workspace.compare": "Compare changes",
	"workspace.permalink": "Link to this run",
	"workspace.previous": "Previous run",
	"workspace.next": "Next run",
	"workspace.input": "Case and input",
	"workspace.result": "Result",
	"workspace.complete": "Open standalone trace",

	"evidence.comparisonOverview": "Comparison overview",
	"evidence.notComparable": "Not comparable",
	"evidence.invalidComparison": "These runs used different or invalid conditions. The recorded answers can be inspected, but they cannot establish an improvement.",
	"evidence.recordedReasons": "Reasons retained in the original decision record:",
	"evidence.comparisonNotices": "Comparison limitations: {count}",
	"evidence.excluded-infrastructure": "Excluded: execution error",
	"evidence.excluded-incomplete": "Excluded: missing repetitions",
	"evidence.excludedNote": "This pair is excluded from the verdict; these answers do not establish an improvement.",
	"evidence.brand": "AHDE Evidence",
	"evidence.comparison": "What changed in the agent",
	"evidence.comparisonIntro": "Compare the answers and actions behind the numbers.",
	"evidence.examples": "Before and after",
	"evidence.exampleNote": "Showing {shown} of {total} task pairs, regressions first. Each card uses the earliest matching recorded repetition; the verdict uses all eligible repetitions.",
	"evidence.baseline": "Before",
	"evidence.candidate": "After",
	"evidence.openRun": "Open full conversation",
	"evidence.noSample": "No matching recorded repetition is available for this task.",
	"evidence.noAnswer": "No final answer is available in the verified trace.",
	"evidence.noInput": "Case input is unavailable.",
	"evidence.checks": "Checks of actions and state",
	"evidence.moreChecks": "{count} more checks in the full conversation",
	"evidence.noTools": "No executed tools recorded",
	"evidence.reportedTools": "Agent-reported tools",
	"evidence.executedTools": "Executed tools",
	"evidence.toolErrors": "Tool errors",
	"evidence.noToolsTrace": "Tool names are unavailable in the verified trace.",
	"evidence.changedScore": "Score across repetitions",
	"evidence.improved": "improved",
	"evidence.regressed": "regressed",
	"evidence.unchanged": "unchanged",
	"evidence.pass": "pass",
	"evidence.fail": "fail",
	"evidence.error": "error",
	"evidence.metadata": "Recorded identities and details",
	"evidence.passRate": "Pass rate",
	"evidence.passed": "Passed",
	"evidence.meanScore": "Mean score",
	"evidence.errors": "Errors",
	"evidence.failureModes": "Failure modes",
	"evidence.allPassRate": "All-pass rate",
	"evidence.taskFlips": "Task score changes",
	"evidence.costRatio": "Cost ratio",
	"evidence.latencyRatio": "Latency ratio",
	"evidence.tokenRatio": "Token ratio",
	"evidence.sealed": "Sealed verdict",
	"evidence.sealedDesign": "{tasks} cases × {repetitions} repetitions",
	"evidence.sealedExcluded": "{count} excluded",
	"evidence.sealedNote": "This is a relative comparison, not an absolute readiness score. Sealed cases, identifiers, and traces are never rendered here.",
	"evidence.sealedUnknown": "pass; the recorded evidence does not establish whether it improved",
	"evidence.noSealed": "No sealed holdout comparison is recorded for this candidate.",
	"evidence.flipNote": "Per-task flips are flags for review; the verdict above comes only from the paired interval.",
	"evidence.noRuns": "No runs match this filter.",
	"evidence.noGraders": "no graders",
	"evidence.traceUnavailable": "trace unavailable",
	"evidence.executedCount": "{count} executed",
	"evidence.reportedCount": "{count} reported",
	"evidence.errorCount": "{count} errors",
	"evidence.filterPlaceholder": "Filter by task id or input text",
	"evidence.filterLabel": "Filter runs",
	"evidence.filterCount": "{shown} of {total} rows",
	"evidence.all": "all",
	"evidence.clearMode": "clear mode filter",
	"evidence.noModes": "No failure modes: the verified diagnosis found nothing to group.",
	"evidence.proposalEligible": "An exact change can be prepared for human review.",
	"evidence.proposalBlocked": "The evidence does not yet support preparing a change. Resolve the measurement issues first.",
	"evidence.design": "{tasks} cases × {repetitions} repetitions · {runs} runs",
	"evidence.model": "Model",
	"evidence.dataset": "Dataset",
	"evidence.user": "user",
	"evidence.assistant": "assistant",
	"evidence.finalAnswer": "final answer",
	"evidence.thinking": "thinking",
	"evidence.tool": "tool",
	"evidence.arguments": "arguments",
	"evidence.result": "result",
	"evidence.clipped": "clipped",
	"evidence.reportedOnly": "agent-reported, not host-verified",
	"evidence.noResult": "no result recorded",
	"evidence.ok": "ok",
	"evidence.noTrace": "No trace is recorded for this run.",
	"evidence.noTurns": "The recorded trace holds no renderable turns.",
	"evidence.noGraderResults": "This run recorded no grader results.",
	"evidence.assertionsSummary": "The record keeps {passed}/{total} assertions; per-assertion evidence is not available for this run.",
	"evidence.jury": "Jury",
	"evidence.juror": "juror",
	"evidence.choice": "choice",
	"evidence.hostNote": "Every sentence above is assembled by the host from recorded fields — the grader results, the bounded trace, the stored diagnosis, and a Candidate's own comparison. No model wrote it.",
	"evidence.systemInstructions": "System instructions",
	"evidence.systemUnavailable": "The Target's system instructions are not recorded in session.jsonl; this transcript starts at the case input.",
	"evidence.caseInput": "Case input",
	"evidence.allRuns": "all runs",
	"evidence.diagnosisDetails": "Read the complete explanation",
	"evidence.traceNotice": "{count} transcript entries rendered{clipped}{omitted}. Credential-shaped text is redacted; the protected artifact on disk is unchanged.",
	"evidence.traceClipped": "; longer content is clipped",
	"evidence.traceOmitted": "; {count} later trace records omitted",
} as const;

export const evidenceRussian: Record<keyof typeof evidenceEnglish, string> = {
	"conversation.number": "Обращение {number}",
	"conversation.selected": "Выбранное обращение",
	"conversation.notGrouped": "Разговор и его проверки доступны. Повторяющиеся проблемы в этом прогоне ещё не разобраны; когда понадобится их сводка, попросите Builder проанализировать прогон.",
	"conversation.expected": "Что требовалось в этом кейсе",
	"conversation.expectedDetails": "Требования к этому кейсу показаны ниже в записанных проверках.",
	"conversation.before": "Что записано до правки",
	"conversation.after": "Что записано после правки",
	"conversation.story": "Ожидание и записанный результат",
	"conversation.changeFiles": "Изменённые файлы: {paths}",
	"conversation.authorHypothesis": "Записанная гипотеза автора",
	"conversation.next": "Что проверить дальше",
	"conversation.nextReview": "Посмотрите общее сравнение, включая ухудшения и исключённые кейсы. Одного выбранного разговора недостаточно для принятия правки.",
	"conversation.nextTerminal": "Вернитесь к Builder в терминале и попросите проверить, можно ли принять эту правку. Он проверит актуальные доказательства и запросит итоговое решение.",
	"conversation.nextInconclusive": "Сравнение пока не даёт определённого ответа. Сначала разберите с Builder ограничения записанных доказательств, затем решайте о принятии правки.",
	"conversation.nextInvalid": "Эти результаты несопоставимы. Попросите Builder устранить различия условий оценки перед новым сравнением.",
	"conversation.openEvaluation": "Открыть все записанные разговоры",
	"conversation.openChanges": "Посмотреть точную правку",
	"conversation.historical": "Записанная оценка по прежним правилам",
	"conversation.historicalMeaning": "Разговоры и результаты сохранены, но правила оценки изменились. Для решения о применении нужен новый прогон.",
	"conversation.historicalRules": "Здесь применялись правила {before}; текущая версия — {after}. Результаты описывают сохранённые разговоры и не разрешают применить правку сегодня.",
	"conversation.historicalAction": "Пересчитать сохранённые разговоры в Builder",
	"conversation.historicalLimit": "Пересчёт сохранит оригиналы и не запустит агента повторно; модели-судьи могут вызываться. Для решения о применении нужен новый прогон, одного ретроспективного пересчёта недостаточно.",
	"workspace.checkCount": "Пройдено {passed}/{total}",
	"workspace.moreFailed": "Ещё проваленных проверок в разборе: {count}",
	"workspace.title": "Разбор оценки",
	"workspace.issues": "Проблемы",
	"workspace.allIssues": "Все записанные прогоны",
	"workspace.observed": "Наблюдения этой оценки",
	"workspace.impact": "Кейсы: {affected}/{total} · прогонов: {runs}",
	"workspace.reproduction": "Сбоев среди сопоставимых наблюдений: {failed}/{total} ({rate})",
	"workspace.issueNote": "Группы описывают записанные сбои. Это не доказанная первопричина и не влияние на пользователей в продакшене.",
	"workspace.runs": "Прогоны",
	"workspace.shown": "Прогонов: {shown} из {total}",
	"workspace.search": "Найти",
	"workspace.searchNote": "Поиск по идентификатору кейса и ограниченному фрагменту его входа.",
	"workspace.inspect": "Разобрать прогон",
	"workspace.inspector": "Разбор разговора",
	"workspace.empty": "Выберите записанный прогон, чтобы изучить разговор и проверки.",
	"workspace.trajectory": "Порядок взаимодействий",
	"workspace.trajectoryNote": "Исходный порядок записи. Длительность инструментов показана, если записана; это не дерево распределённых вызовов.",
	"workspace.checks": "Проверки и объяснение по записи",
	"workspace.more": "Детали оценки и ограничения",
	"workspace.keyboard": "Клавиша табуляции — переход между элементами. На ссылке прогона ↑ / ↓ — переход по списку; Enter — открыть.",
	"workspace.focusRuns": "К прогонам",
	"workspace.focusTrace": "К разговору",
	"workspace.outsideFilter": "Прогон из этой ссылки принадлежит оценке, но не входит в текущую выборку.",
	"workspace.compare": "Сравнить изменения",
	"workspace.permalink": "Ссылка на этот прогон",
	"workspace.previous": "Предыдущий прогон",
	"workspace.next": "Следующий прогон",
	"workspace.input": "Кейс и обращение",
	"workspace.result": "Результат",
	"workspace.complete": "Открыть отдельную запись",

	"evidence.comparisonOverview": "Общее сравнение",
	"evidence.notComparable": "Несопоставимо",
	"evidence.invalidComparison": "Условия этих прогонов различаются или недействительны. Ответы можно изучить, но они не доказывают улучшение.",
	"evidence.recordedReasons": "Основания из исходной записи решения:",
	"evidence.comparisonNotices": "Ограничения сравнения: {count}",
	"evidence.excluded-infrastructure": "Исключён: ошибка выполнения",
	"evidence.excluded-incomplete": "Исключён: не хватает повторов",
	"evidence.excludedNote": "Пара исключена из вердикта; эти ответы не доказывают улучшение.",
	"evidence.brand": "AHDE · Доказательства",
	"evidence.comparison": "Что изменилось в агенте",
	"evidence.comparisonIntro": "Сравните ответы и действия, которые стоят за цифрами.",
	"evidence.examples": "До и после",
	"evidence.exampleNote": "Показано {shown} из {total} пар кейсов, сначала ухудшения. В карточке — первый общий записанный повтор; вердикт учитывает все допустимые повторы.",
	"evidence.baseline": "До правки",
	"evidence.candidate": "После правки",
	"evidence.openRun": "Открыть весь диалог",
	"evidence.noSample": "Для этого кейса нет записанного повтора, общего для двух версий.",
	"evidence.noAnswer": "В проверенной записи нет доступного итогового ответа.",
	"evidence.noInput": "Вход кейса недоступен.",
	"evidence.checks": "Проверки действий и состояния",
	"evidence.moreChecks": "Ещё {count} проверок в полном диалоге",
	"evidence.noTools": "Выполненные инструменты не записаны",
	"evidence.reportedTools": "Инструменты со слов агента",
	"evidence.executedTools": "Выполнено инструментов",
	"evidence.toolErrors": "Ошибки инструментов",
	"evidence.noToolsTrace": "В проверенной записи нет доступных имён инструментов.",
	"evidence.changedScore": "Балл по всем повторам",
	"evidence.improved": "стало лучше",
	"evidence.regressed": "стало хуже",
	"evidence.unchanged": "без изменений",
	"evidence.pass": "пройдено",
	"evidence.fail": "не пройдено",
	"evidence.error": "ошибка",
	"evidence.metadata": "Идентификаторы и детали записи",
	"evidence.passRate": "Доля успешных",
	"evidence.passed": "Пройдено",
	"evidence.meanScore": "Средний балл",
	"evidence.errors": "Ошибки",
	"evidence.failureModes": "Типы сбоев",
	"evidence.allPassRate": "Доля успешных прогонов",
	"evidence.taskFlips": "Изменение балла кейсов",
	"evidence.costRatio": "Изменение цены",
	"evidence.latencyRatio": "Изменение задержки",
	"evidence.tokenRatio": "Изменение токенов",
	"evidence.sealed": "Закрытый экзамен",
	"evidence.sealedDesign": "Кейсов: {tasks} × повторов: {repetitions}",
	"evidence.sealedExcluded": "исключено: {count}",
	"evidence.sealedNote": "Это сравнение версий, а не абсолютная оценка готовности. Кейсы, идентификаторы и диалоги закрытого экзамена здесь не показываются.",
	"evidence.sealedUnknown": "пройден; запись не позволяет уточнить, доказано ли улучшение",
	"evidence.noSealed": "Для этого кандидата не записано сравнение на закрытом экзамене.",
	"evidence.flipNote": "Изменения отдельных кейсов требуют внимания; вердикт выше определяется только парным доверительным интервалом.",
	"evidence.noRuns": "Нет прогонов по этому фильтру.",
	"evidence.noGraders": "нет проверок",
	"evidence.traceUnavailable": "запись недоступна",
	"evidence.executedCount": "выполнено: {count}",
	"evidence.reportedCount": "со слов агента: {count}",
	"evidence.errorCount": "ошибок: {count}",
	"evidence.filterPlaceholder": "Найти кейс или текст обращения",
	"evidence.filterLabel": "Поиск по прогонам",
	"evidence.filterCount": "Строк: {shown} из {total}",
	"evidence.all": "все",
	"evidence.clearMode": "сбросить тип сбоя",
	"evidence.noModes": "Типы сбоев не найдены: проверенный диагноз не обнаружил ошибок для группировки.",
	"evidence.proposalEligible": "Можно подготовить точную правку для вашего ревью.",
	"evidence.proposalBlocked": "Доказательств пока недостаточно для правки. Сначала нужно устранить проблемы измерения.",
	"evidence.design": "Кейсов: {tasks} × повторов: {repetitions} · прогонов: {runs}",
	"evidence.model": "Модель",
	"evidence.dataset": "Датасет",
	"evidence.user": "клиент",
	"evidence.assistant": "агент",
	"evidence.finalAnswer": "итоговый ответ",
	"evidence.thinking": "рассуждение",
	"evidence.tool": "инструмент",
	"evidence.arguments": "аргументы",
	"evidence.result": "результат",
	"evidence.clipped": "сокращён",
	"evidence.reportedOnly": "со слов агента, хостом не подтверждено",
	"evidence.noResult": "результат не записан",
	"evidence.ok": "успешно",
	"evidence.noTrace": "Диалог этого прогона не записан.",
	"evidence.noTurns": "В записи нет доступных реплик.",
	"evidence.noGraderResults": "В этом прогоне нет результатов проверок.",
	"evidence.assertionsSummary": "В записи сохранено {passed}/{total} утверждений; отдельные обоснования для них недоступны.",
	"evidence.jury": "Коллегия судей",
	"evidence.juror": "судья",
	"evidence.choice": "выбор",
	"evidence.hostNote": "Все пояснения собраны хостом из результатов проверок, ограниченной записи диалога, сохранённого диагноза и сравнения кандидата. Модель их не сочиняла.",
	"evidence.systemInstructions": "Системные инструкции",
	"evidence.systemUnavailable": "Системные инструкции агента не сохранены в записи; диалог начинается с входа кейса.",
	"evidence.caseInput": "Вход кейса",
	"evidence.allRuns": "все прогоны",
	"evidence.diagnosisDetails": "Полное объяснение",
	"evidence.traceNotice": "Показано записей диалога: {count}{clipped}{omitted}. Строки, похожие на ключи доступа, скрыты; исходный артефакт на диске не изменён.",
	"evidence.traceClipped": "; длинный текст сокращён",
	"evidence.traceOmitted": "; пропущено последующих записей: {count}",
};
