/** A scoped work surface. Standalone traces, replay and exported HTML retain their shared theme. */
export const WORKSPACE_STYLES = `
.evidence-workspace{color-scheme:dark;--bg:#111216;--surface:#17191e;--surface2:#1c1f26;--sunken:#14161b;--line:#2a2d35;--line-strong:#414650;--text:#e8e9ed;--muted:#a6aab6;--faint:#898e9b;--accent:#b4b9ff;--accent-soft:#292b42;--pass:#7ad8af;--pass-soft:#193229;--fail:#ffa2ab;--fail-soft:#3a222a;--error:#edc485;--error-soft:#392f20;font-size:14px}
.evidence-workspace .wrap{max-width:2000px;padding:0 24px 24px}
.evidence-workspace .topbar{position:static;background:var(--bg);padding:15px 24px;font-size:12px;border:0}
.evidence-workspace a:focus-visible,.evidence-workspace button:focus-visible,.evidence-workspace [tabindex]:focus-visible{outline:2px solid var(--accent);outline-offset:3px}
.evidence-workspace [id]{scroll-margin-top:16px}
.evidence-workspace button,.evidence-workspace input{font:inherit}
.w-skip{height:0;overflow:visible;position:relative;z-index:10}
.w-skip a{position:absolute;left:0;top:-120px;padding:12px;background:var(--surface);border:1px solid var(--accent)}
.w-skip a:focus{top:0}.w-skip a+a{left:180px}
.w-header{display:flex;gap:24px;align-items:center;flex-wrap:wrap;padding:18px 0 22px}
.w-eyebrow{font-size:10px;text-transform:uppercase;letter-spacing:.12em;font-weight:650;color:var(--muted);margin:0 0 7px}
.w-header h1{font-size:27px;letter-spacing:-.03em;line-height:1.2;margin:0 0 6px}
.w-subtitle{font-size:12px;color:var(--muted);margin:0}
.w-context{display:flex;flex-direction:column;gap:2px;font-size:11px;color:var(--muted);max-width:240px;overflow-wrap:anywhere}
.w-summary{display:flex;gap:24px;margin:0 0 0 auto;flex-wrap:wrap;font-variant-numeric:tabular-nums}
.w-summary dt{font-size:10px;color:var(--muted);margin-bottom:3px}.w-summary dd{font-size:24px;line-height:1.25;font-weight:550;letter-spacing:-.04em;margin:0}
.w-eval-details{font-size:12px;color:var(--muted);margin:0 0 17px}.w-eval-details summary{cursor:pointer;width:fit-content}.w-eval-details[open]{padding:14px 18px;background:var(--surface);border:1px solid var(--line);border-radius:9px}.w-eval-details[open] summary{margin-bottom:12px}.w-eval-details pre{white-space:pre-wrap;overflow-wrap:anywhere}
.eval-workspace{display:grid;grid-template-columns:228px minmax(340px,.95fr) minmax(390px,1.15fr);border:1px solid var(--line);border-radius:12px;overflow:hidden;background:var(--surface);align-items:start}
.w-panel-title{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:18px 16px;border-bottom:1px solid var(--line)}
.w-panel-title h2{font-size:13px;font-weight:650;margin:0}.w-count{font-size:11px;color:var(--muted);font-variant-numeric:tabular-nums}
.w-issues{min-width:0;align-self:stretch;background:var(--sunken)}
.w-all{display:flex;justify-content:space-between;gap:12px;padding:13px 14px;margin:8px;font-size:12px;color:var(--muted);border:1px solid transparent;border-radius:6px}
.w-all span{font-variant-numeric:tabular-nums}.w-all.selected{background:var(--surface2);border-color:var(--line);color:var(--text)}
.w-issue-list{margin:0;padding:0 8px;list-style:none;display:grid;gap:7px}
.w-issue{display:block;padding:13px 12px;border:1px solid var(--line);border-radius:7px;color:var(--text);background:var(--surface)}
.w-issue:hover,.w-all:hover{background:var(--surface2);text-decoration:none}.w-issue.selected{background:var(--accent-soft);border-color:var(--accent)}
.w-issue-title{display:block;font-size:13px;font-weight:550;line-height:1.4;margin-bottom:12px;overflow-wrap:anywhere}
.w-issue-impact{display:block;font-size:11px;font-variant-numeric:tabular-nums}.w-issue-rate{display:block;color:var(--muted);font-size:10px;line-height:1.5;margin:4px 0 10px}
.w-issue-severity{font-size:10px;color:var(--muted)}
.w-note{color:var(--muted);font-size:11px;line-height:1.6;margin:0;padding:15px 16px;overflow-wrap:anywhere}
.w-comparisons{margin:8px 16px 22px;border-top:1px solid var(--line);padding-top:18px}.w-comparisons h3{font-size:11px;color:var(--muted);margin-bottom:12px}.w-comparisons a{display:block;font-size:12px;overflow-wrap:anywhere;margin-bottom:10px}.w-comparisons .w-secondary{font-size:11px;color:var(--muted);margin-bottom:18px}
.w-runs{min-width:0;border-left:1px solid var(--line);border-right:1px solid var(--line);align-self:stretch}
.w-finding{margin:14px 14px 0;padding:13px 14px;background:var(--accent-soft);border:1px solid var(--line-strong);border-radius:7px}.w-finding h3{font-size:13px;margin:0 0 7px}.w-finding p{font-size:12px;line-height:1.6;overflow-wrap:anywhere;margin-bottom:0}.w-finding details{font-size:11px;margin-top:10px}.w-finding summary{cursor:pointer}.w-finding details p{margin-top:8px}
.w-run-controls{padding:14px}.w-search{display:flex;gap:7px}.w-search input{width:100%;min-width:0;color:var(--text);border:1px solid var(--line-strong);background:var(--bg);border-radius:6px;padding:8px 10px;font-size:12px}.w-search button{flex-shrink:0;border:1px solid var(--line-strong);background:var(--surface2);color:var(--text);padding:7px 10px;border-radius:6px;cursor:pointer;font-size:12px}.w-search button:hover{border-color:var(--accent)}
.w-filters{display:flex;gap:5px;margin-top:11px;flex-wrap:wrap}.w-filters a{font-size:11px;border:1px solid transparent;border-radius:5px;padding:4px 9px;color:var(--muted)}.w-filters a[aria-current]{background:var(--surface2);color:var(--text);border-color:var(--line-strong)}.w-filters a:hover{background:var(--surface2);text-decoration:none}
.w-table-scroll{overflow:auto;max-height:650px;scrollbar-width:thin}.w-table{border-collapse:collapse;width:100%;text-align:left;table-layout:fixed}.w-table th{font-size:10px;font-weight:500;color:var(--muted);padding:9px 11px;background:var(--sunken);border-block:1px solid var(--line);position:sticky;top:0;z-index:1}.w-table th:nth-child(1){width:44%}.w-table th:nth-child(2){width:17%}.w-table th:nth-child(3){width:24%}.w-table th:nth-child(4){width:15%;text-align:right}
.w-table td{padding:15px 11px;vertical-align:top;border-bottom:1px solid var(--line)}.w-table tr.selected{background:var(--accent-soft)}.w-table tr.selected td:first-child{box-shadow:inset 3px 0 var(--accent)}.w-table tr:hover{background:var(--surface2)}
.w-run-link{display:block;font-size:12px;font-weight:550;color:var(--text);overflow-wrap:anywhere}.w-run-link small{display:block;font-size:10px;color:var(--muted);font-weight:400;margin-top:3px}.w-run-link:hover{color:var(--accent)}.w-case p{font-size:11px;line-height:1.65;color:var(--muted);margin:8px 0 0;overflow-wrap:anywhere;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}
.w-score{display:block;color:var(--muted);font-size:11px;margin-top:7px;font-variant-numeric:tabular-nums}.w-graders{overflow-wrap:anywhere}.w-check-count{display:block;font-size:11px;color:var(--muted);margin-bottom:5px;font-variant-numeric:tabular-nums}.w-graders .gchip{font-size:9px;padding:1px 4px;margin-right:0;max-width:100%;white-space:normal}.w-graders small,.w-resource small{display:block;font-size:10px;color:var(--muted);margin-top:6px}.w-resource{font-size:11px;text-align:right;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.w-resource small{font-size:10px}.w-table .chip{font-size:10px;padding:1px 5px}
.w-inspector{min-width:0;background:var(--surface)}.w-inspector-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:19px 21px 14px}.w-inspector-head h2{font-size:19px;overflow-wrap:anywhere;margin:0}.w-inspector-head h2 small{display:block;margin-top:5px;color:var(--muted);font-size:11px;font-weight:400}.w-inspector-head .chip{flex-shrink:0}
.w-trace-nav{display:flex;gap:15px;padding:0 21px 15px;align-items:center;flex-wrap:wrap}.w-trace-nav a{font-size:11px;color:var(--muted)}.w-trace-nav a:hover{color:var(--accent)}.w-run-arrows{display:flex;gap:8px;margin-left:auto}.w-run-arrows a{border:1px solid var(--line-strong);padding:2px 8px;border-radius:4px;font-size:13px}
.w-run-metrics{margin:0;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));padding:12px 21px;gap:10px;border-block:1px solid var(--line);background:var(--sunken);font-variant-numeric:tabular-nums}.w-run-metrics dt{font-size:10px;color:var(--muted)}.w-run-metrics dd{font-size:13px;margin:4px 0 0;overflow-wrap:anywhere}
.w-inspector-body{padding:17px 20px 22px;max-height:780px;overflow:auto;scrollbar-width:thin}.w-inspector-body .w-note{padding:10px 0}.w-checks{border:1px solid var(--line);border-radius:7px;padding:11px 12px;margin:0 0 12px;font-size:12px}.w-checks>summary{cursor:pointer;font-weight:500;overflow-wrap:anywhere}.w-checks>summary span{float:right;color:var(--muted);margin-left:10px}.w-checks[open]>summary{margin-bottom:13px}.w-checks .card{padding:12px;font-size:12px}.w-checks .card h3{font-size:12px}.w-checks .why{padding:12px;font-size:12px;margin-top:12px}.w-checks pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px}.w-checks .scroll{max-height:280px}.w-checks .scroll td.wrapcell{min-width:180px}
.w-conversation-head{display:flex;justify-content:space-between;gap:15px;align-items:baseline;margin:24px 0 12px}.w-conversation-head h3{font-size:13px;margin:0}.w-conversation-head details{font-size:10px;color:var(--muted);text-align:right}.w-conversation-head summary{cursor:pointer}.w-conversation-head details[open]{max-width:230px}
.w-sequence{display:flex;gap:6px;overflow:auto;padding:0 0 15px;margin-bottom:3px;scrollbar-width:thin}.w-sequence a{display:flex;align-items:center;gap:5px;flex-shrink:0;padding:5px 8px;border:1px solid var(--line);border-radius:5px;color:var(--muted);font-size:10px}.w-sequence a span{color:var(--faint);font-variant-numeric:tabular-nums}.w-sequence a small{font-size:9px}.w-sequence .w-step-error{color:var(--error);border-color:var(--error)}.w-sequence a:hover{background:var(--surface2);text-decoration:none}
.w-inspector .turn{padding:14px 15px;margin-bottom:12px;border-radius:8px;background:var(--sunken)}.w-inspector .turn.final{background:var(--surface2);border-color:var(--line-strong)}.w-inspector .turn .who{font-size:10px;line-height:1.5;gap:8px;flex-wrap:wrap;margin-bottom:10px;color:var(--muted)}.w-inspector .turn .spoken{font-family:var(--sans);font-size:13px;line-height:1.75}.w-inspector .turn pre{font-size:11px;line-height:1.65;max-height:440px}.w-inspector .turn details{font-size:11px}.w-inspector .turn:target{outline:2px solid var(--accent);outline-offset:2px}
.w-run-error{padding:14px;background:var(--error-soft);border:1px solid var(--error);border-radius:7px;margin-bottom:14px}.w-run-error h3{font-size:12px}.w-run-error pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px}.w-empty{padding:40px 26px;color:var(--muted)}.w-empty h2{font-size:17px}.w-empty p{font-size:13px}
.w-reading{padding:17px 16px;background:var(--sunken);border:1px solid var(--line-strong);border-radius:8px;margin-bottom:18px}.w-reading>h3{font-size:19px;line-height:1.4;letter-spacing:-.02em;margin:0 0 16px}.w-reading h4{font-size:10px;letter-spacing:.03em;font-weight:600;color:var(--muted);margin:0 0 6px}.w-reading p{font-size:12px;line-height:1.6;margin:0 0 7px;overflow-wrap:anywhere}.w-reading blockquote{border-left:2px solid var(--accent);margin:0 0 16px;padding:1px 0 1px 12px}.w-reading blockquote>span{font-size:10px;color:var(--muted)}.w-reading blockquote p{font-size:14px;margin:5px 0}.w-reading blockquote small{font-size:10px;color:var(--muted)}.w-reading-observed{margin-bottom:12px}.w-reading details{font-size:11px;color:var(--muted);margin:8px 0 14px}.w-reading details>summary{cursor:pointer}.w-reading details[open]>summary{margin-bottom:12px}.w-reading-reason{padding:9px;border:1px solid var(--line);border-radius:5px}.w-reading-reason span{display:block;font:10px var(--mono);color:var(--muted);margin-bottom:5px}.w-reading-reason q{font-size:11px;overflow-wrap:anywhere}.w-reading-change{border-top:1px solid var(--line);padding-top:12px;margin-top:12px}.w-reading-limit{margin-top:12px}.w-reading-limit p{font-size:10px;color:var(--muted);line-height:1.6}.w-reading p:last-child{margin-bottom:0}
@media(min-width:1500px){.eval-workspace{grid-template-columns:260px minmax(420px,1fr) minmax(460px,1.1fr)}.w-inspector-body{max-height:calc(100vh - 355px);min-height:430px}.w-table-scroll{max-height:calc(100vh - 400px);min-height:340px}}
@media(max-width:1190px){.evidence-workspace .wrap{padding:0 16px 20px}.eval-workspace{grid-template-columns:200px minmax(0,1fr)}.w-inspector{grid-column:1/-1;border-top:1px solid var(--line)}.w-inspector-body{max-height:none;display:block}.w-runs{border-right:0}.w-table-scroll{max-height:490px}.w-summary{gap:18px}.w-summary dd{font-size:21px}.w-context{display:none}.w-inspector-head h2 small{display:inline;margin-left:12px}.w-inspector .turn{max-width:100%}}
@media(max-width:640px){.evidence-workspace .wrap{padding:0 10px 14px}.evidence-workspace .topbar{padding:12px 14px;gap:7px;font-size:10px}.w-header{padding:12px 5px 18px;gap:18px}.w-header h1{font-size:25px}.w-summary{margin:0;width:100%;justify-content:space-between;gap:12px}.w-summary dd{font-size:21px}.w-summary dt{font-size:9px}.w-subtitle{font-size:11px}.w-eval-details{margin-left:5px;font-size:11px}.eval-workspace{display:block}.w-panel-title{padding:15px 14px}.w-issues{border-bottom:1px solid var(--line)}.w-issue-list{display:flex;overflow:auto;padding:0 8px 10px;scrollbar-width:thin}.w-issue-list li{min-width:240px;max-width:280px}.w-issue-title{font-size:12px;margin-bottom:8px}.w-issue-rate{font-size:10px;margin-bottom:6px}.w-issues>.w-note{padding-top:7px;font-size:10px}.w-comparisons{display:flex;gap:12px;flex-wrap:wrap;margin:0 15px 15px;padding-top:12px}.w-comparisons h3{width:100%;margin:0}.w-comparisons a,.w-comparisons .w-secondary{margin:0;font-size:10px;max-width:100%}.w-runs{border:0}.w-table-scroll{max-height:430px}.w-table th,.w-table td{padding:12px 8px}.w-table th:nth-child(1){width:46%}.w-table th:nth-child(2){width:20%}.w-table th:nth-child(3){width:34%}.w-table th:nth-child(4),.w-table td:nth-child(4){display:none}.w-keyboard{display:none}.w-inspector-head{padding:20px 15px 12px}.w-inspector-head h2 small{display:block;margin:5px 0 0}.w-trace-nav{padding:0 15px 15px;gap:10px}.w-trace-nav a{font-size:10px}.w-run-metrics{padding:12px 15px}.w-run-metrics dt{font-size:9px}.w-inspector-body{padding:15px 12px}.w-inspector .turn{padding:13px 12px}.w-inspector .turn .spoken{font-size:13px}.w-sequence a{min-height:34px}.w-inspector{scroll-margin-top:10px}.w-inspector:target{outline:2px solid var(--accent);outline-offset:-2px}}
@media(prefers-reduced-motion:reduce){.evidence-workspace *{scroll-behavior:auto!important}}
@media print{.evidence-workspace{color-scheme:light;--bg:#fff;--surface:#fff;--sunken:#fff;--surface2:#fff;--text:#000;--muted:#444;--accent:#333;--line:#bbb}.eval-workspace{display:block}.w-inspector-body,.w-table-scroll{max-height:none;overflow:visible}.w-run-controls,.w-skip,.w-keyboard,.w-sequence{display:none}.w-issues,.w-runs,.w-inspector{border:0}.w-inspector .turn{break-inside:avoid}}
`;
